[tool.black]
line-length = 88
target-version = ["py311"]
include = "\\.(py)$"
exclude = "/(\\.git|\\.venv|migrations|__pycache__)/"

[tool.isort]
profile = "black"
line_length = 88
known_first_party = ["app", "tests"]
